### ISSUE TITLE
button type should be "submit" instead of "button"

### ISSUE THREAD

**Issue by sagayev** [CodingForEverybody/learn-wagtail#11]
Hi Kalob,
Really great content. Thank you.
Just found a little typo, which didn't allow me to submit the contact form. The ugly version, which you were showing in the video was fine. But after adding style, you somehow changed the  input tag to button tag, but changed the type from "submit" to "button".

```
<button type="button" class="btn btn-success">
                Submit Form
 </button>
```

```
<button type="submit" class="btn btn-success">
                Submit Form
 </button>
```

**Comment by KalobTaulien** [comment]
Thanks, good find! I added a comment to the commit code here https://github.com/CodingForEverybody/learn-wagtail/commit/d67bc5659ca023c21d8a9f01d30604f6d67cd2d6#r37762436
