### ISSUE TITLE
Consuming API in Wagtail

### ISSUE THREAD

**Issue by maxwaiyaki** [CodingForEverybody/learn-wagtail#4]
How would you go about consuming an API in Wagtail? e.g a recipe api  to enable you to embed recipes to blog posts from the admin dashboard?

**Comment by KalobTaulien** [comment]
You'd want to enable the Wagtail V2 API and add APIFields to your Page models. 

I have two videos on how to do this exactly:
https://www.youtube.com/watch?v=9SNLd44Eb7M&list=PLMQHMcNi6ocsS8Bfnuy_IDgJ4bHRRrvub&index=36 and
https://www.youtube.com/watch?v=KURq8uhmeBg&list=PLMQHMcNi6ocsS8Bfnuy_IDgJ4bHRRrvub&index=37

And then you can use a framework like Angular, Vue.js or React to ajax the API endpoints and modify the DOM as needed.

**Comment by maxwaiyaki** [comment]
No, I'd want to consume an external api in wagtail. .eg the youtube api

**Comment by KalobTaulien** [comment]
It's the same as consuming any other API in Python, that's not really a Wagtail-specific thing.
