### ISSUE TITLE
would you please finish @todo in blog_listing_page.html?

### ISSUE THREAD

**Issue by fudongyu** [CodingForEverybody/learn-wagtail#6]
Hi, I am following your course on youtube. 
would you please finish this @todo ?
 {# @todo add a summary field to BlogDetailPage; make it a RichTextField with only Bold and Italic enabled. #}

I do not figure out how to do that. 
btw, thanks to your course again

**Comment by wolfpirker** [comment]
Hello,
isn't this covered in this tutorial already?
[https://learnwagtail.com/course/how-add-richtext-streamfield-your-wagtail-cms-page/](url)

**Comment by KalobTaulien** [comment]
Hi @fudongyu 

@wolfpirker is right, it's covered in the RichText lesson. It's also covered in several other areas as well. You could simply add a `summary = models.TextField()` to your Blog Page model as well and use `{{ post.summary }}` in the `blog_listing_page.html` loop.
